on:
  pull_request:
    branches:
      - master
      - staging
      - develop

name: Continuous integration (PR)

jobs:
  version-check:
    if: github.base_ref == 'staging' || github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --all --tags

      - name: Check Release Version (staging)
        if: github.base_ref == 'staging'
        uses: thebongy/version-check@v1
        with:
          file: package.json
          tagFormat: v${version}-beta
        id: version_check_staging

      - name: Check Release Version (master)
        if: github.base_ref == 'master'
        uses: thebongy/version-check@v1
        with:
          file: package.json
          tagFormat: v${version}
        id: version_check_master
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --all --tags

      - name: Check Release Version
        uses: thebongy/version-check@v1
        with:
          file: package.json
        id: version_check

      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm ci

      - name: Linting and tests
        run: npm run test:prod

      - name: Build
        run: npm build

      - name: Create tar
        run: npm pack

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: juno-node@v${{ steps.version_check.outputs.releaseVersion }}-alpha
          path: ./juno-node-${{ steps.version_check.outputs.releaseVersion }}.tgz
